### ISSUE TITLE
TinyGo don't support grpc-go!

### ISSUE THREAD

**Issue by jmzwcn** [syumai/workers#109]
TinyGo don't support grpc-go! any suggestion?

**Comment by syumai** [comment]
I don't think there are any gRPC implementation options that work with TinyGo.

In Go (not TinyGo), I confirmed that connect-go works on Cloudflare Workers.
https://github.com/syumai/workers-playground/tree/main/connect-go-emoji-server

**Comment by syumai** [comment]
This does not appear to be a syumai/workers' issue, so I'll close this issue.
