### ISSUE TITLE
Support HTTP Request and Cron Trigger in Single Worker

### ISSUE THREAD

**Issue by ben-krieger** [syumai/workers#127]
Currently `cron.ScheduleTask` and `workers.Serve` cannot both be used within the same `func main`, because they both call `ready`, causing a race condition.

Also, `cron.ScheduleTask` blocks indefinitely and `workers.Serve` blocks until the request is closed, so there needs to be a way to know the trigger type in order to decide if/when to exit main.

I don't think there's a Cloudflare restriction that a Worker can only be a Cron Trigger or HTTP Request handler, but I'm new to the Workers platform, so correct me if I'm wrong.

Obviously the workaround to this issue is to create two Workers, but the problem I'm solving for is keeping "Getting Started"-type documentation concise and being able give an example with a single `main.go` and `wrangler.toml` is highly beneficial.

**Comment by meandnano** [comment]
Yeah, this should not be a cloudflare restriction. In fact, in my implementation of [Queues consumer](https://github.com/meandnano/workers/blob/feature/consumer/cloudflare/queues/consumer.go#L75) I've introduced 2 versions of the `Consume` function. One that blocks (just as `workers.Serve`) another that doesn't, specifically to use multiple handlers in one worker. Maybe that approach could be extended to other APIs. What do you think @syumai?

**Comment by syumai** [comment]
Yes, this is not a Cloudflare limitation.
All we need to do is simply expose multiple handlers from `worker.mjs`.
https://github.com/syumai/workers/blob/main/cmd/workers-assets-gen/assets/common/worker.mjs

The non-blocking API proposed by @meandnano looks fine to me.
The blocking functionality of the current implementation (`ready(); <-closeCh`) should be separated and made common, like `Wait()`, `Ready()`, or `WaitForReady()`.

**Comment by syumai** [comment]
@ben-krieger @meandnano This feature has been released as v0.27.0, thanks!
https://github.com/syumai/workers/releases/tag/v0.27.0
