### ISSUE TITLE
"A hanging promise was cancelled" in Workers Runtime

### ISSUE THREAD

**Issue by HumamAlhusaini** [syumai/workers#136]
I'm currently facing an error 

```
[ERROR] A hanging Promise was canceled. This happens when the worker runtime is waiting for a Promise from JavaScript to resolve, but has detected that the Promise cannot possibly ever resolve because all code and events related to the Promise's I/O context have already finished.


[wrangler:inf] GET / 500 Internal Server Error (16ms)
✘ [ERROR] Uncaught (in response) Error: The script will never generate a response.
```

After doing some research, I came across [this](https://community.cloudflare.com/t/a-hanging-promise-was-canceled-rust-wasm-worker/282471/8) community post about a similar issue, except relating to rust and wasm_bindgen

Kenton Varda, the Cloudflare tech lead explains this error.
> This message happens when the Workers Runtime determines that the request is not done yet (no response has been returned), but it also isn’t waiting on anything anymore (e.g. there are no outstanding fetch() requests, setTimeout(), etc.), therefore it decides that the request will never complete. The runtime makes this determination on a per-request basis, even if there are multiple requests running in the same isolate.

Later @nilslic recommend this solution to put in worker.js
```
addEventListener('fetch', event => {
  event.respondWith(handleRequest(event.request))
})

// instantiate these once, and await the Promise returned by `wasm_bindgen(wasm)` inside the request handler.
const { handle } = wasm_bindgen;
const instance =  wasm_bindgen(wasm);

/**
 * Fetch and log a request
 * @param {Request} request
 */
async function handleRequest(request) {
    await instance; // not sure if there is a more optimal way to check if this is resolved with some conditional?

    const objectWithAsyncMethod = {
      run: () => new Promise(resolve => setTimeout(resolve, 10))
    };

    const greeting = await handle(objectWithAsyncMethod);
    return new Response(greeting, {status: 200});
}
```

They explain
>after some investigating, you can accomplish this by updating your code to await the result of `wasm_bindgen(wasm)` on a per-request basis

My suspicion is that there is an issue with the worker.js. I will be testing to see what I can do, but I need to go right now. I'll later reply to this post with my ready github repo, as it is not ready yet.

Thanks.

**Comment by syumai** [comment]
@HumamAlhusaini Could you provide some repro code or a snippet of your implementation?

**Comment by HumamAlhusaini** [comment]
@syumai https://github.com/HumamAlhusaini/syumia-workers-turso-integration

**Comment by syumai** [comment]
Without `workers.Serve`, syumai/workers can't process any HTTP requests.
`os.Exit(1)` does not seem to work properly. (Because it's not an ordinary process, it's Wasm.)

**Comment by syumai** [comment]
Please check usage:
https://github.com/syumai/workers?tab=readme-ov-file#usage

**Comment by HumamAlhusaini** [comment]
Oh, thank you. Definitely should've read the docs a bit more carefully.

**Comment by HumamAlhusaini** [comment]
@syumai I updated my code so it sends an http request instead of libsql and added workers.serve(nil). However I am still getting the same error with an addtional error of "netdev not set". Can you see if this is an error on your side as well? This is the [repo] (https://github.com/HumamAlhusaini/syumia-workers-turso-integration)

**Comment by syumai** [comment]
syumai/workers handles HTTP request, so `http.ListenAndServe(":8787", nil)` is not necessary.

**Comment by syumai** [comment]
Please check examples:
https://github.com/syumai/workers/blob/main/_examples/hello/main.go

**Comment by HumamAlhusaini** [comment]
@syumai It seems that I am still getting the same error "Netdev not set", I'm currently trying to reproduce this error so I can see if it is related to wrangler or your repo.

I have made another test folder to see if I can make a http request using "syscall/js" instead of "net/http" without including wrangler and your repo in the mix. Lo  and behold, it started working! Now my goal is to to reproduce this "Netdev not set" error in my test environment so I can understand if it's an issue with wrangler, your repo, or wasm.

**Comment by syumai** [comment]
@HumamAlhusaini Could you confirm that a clean project using [tinygo template](https://github.com/syumai/workers/tree/main/_templates/cloudflare/worker-tinygo) works?

**Comment by HumamAlhusaini** [comment]
@syumai Yes, it does work.

**Comment by syumai** [comment]
`net/http` may causes problem for tinygo. Then you can use https://github.com/syumai/tinyutil.
https://pkg.go.dev/github.com/syumai/tinyutil@v0.3.2/httputil

**Comment by HumamAlhusaini** [comment]
Thanks
