### ISSUE TITLE
Add template of Cron Triggers worker

### ISSUE THREAD

**Issue by syumai** [syumai/workers#49]
* For convinience, add Cron Triggers worker template into `_templates/cloudflare` directory.

**Comment by vhespanha** [comment]
Can i take this one?

**Comment by syumai** [comment]
@vhespanha Thank you!

**Comment by vhespanha** [comment]
Hey!

Gave it a try, mind taking a look? [ #118](https://github.com/syumai/workers/pull/118) (Opened it as draft because this is my first open-source PR)

Thank you.

**Comment by syumai** [comment]
@vhespanha I'll check this later, thanks!

**Comment by syumai** [comment]
@vhespanha I checked #118 and it seemed to be mostly fine.
Just a small fix, please write TinyGo as `tinygo` instead of `tiny-go`. (In the [official repository](https://github.com/tinygo-org/tinygo) it is written as `tinygo`.)
Once you fix the PR, please open it!
I will check it again after that. Thank you!!

**Comment by vhespanha** [comment]
Hey, sorry for the oversight. Fixed it and pushed again.

**Comment by syumai** [comment]
@vhespanha Thank you! I've merged the PR! 🚀
