### ISSUE TITLE
Add template of Cloudflare Pages

### ISSUE THREAD

**Issue by syumai** [syumai/workers#51]
* For convinience, add template of Cloudflare Pages.
* This requires #50.

**Comment by syumai** [comment]
#50 has been done.

A template based on [pages-function example](https://github.com/syumai/workers/tree/main/_examples/pages-functions) is wanted.

**Comment by AdjectiveAllison** [comment]
I'd love to do this but I'm unsure what the best approach would be to create a template. 

Would it just be some manual file movement/changes into the templates directory? The Makefile would need to be updated to use the direct path to the asset gen and maybe something in wrangler.toml needs to be changed?

Could I help write something that moves your examples to templates automatically perhaps?

**Comment by syumai** [comment]
@AdjectiveAllison 

Thank you for expressing your willingness to contribute.

For this task, there is no need to modify the core code of `syumai/workers`.
The following tasks are expected:

* Create `_templates/cloudflare/pages-tinygo`
* Move the contents of `_examples/pages-functions` to the above directory and simplify the content
  - For example, we would like to remove specific terms like `syumai` in `/api/hello?name=syumai`.
* Adjust `wrangler.toml` and `README.md` to have similar content as `worker-tinygo`
  - We want it to work with the command `wrangler generate my-app syumai/workers/_templates/cloudflare/pages-tinygo`
  - Although the `wrangler generate` command has been deprecated in wrangler v3, there is no alternative yet, so it is still acceptable to continue using it.

If you can handle these changes, it would be greatly appreciated. Thank you for your comment.

**Comment by syumai** [comment]
#62 resolved this issue.
