### ISSUE TITLE
Add TCP sockets support

### ISSUE THREAD

**Issue by syumai** [syumai/workers#56]
https://blog.cloudflare.com/workers-tcp-socket-api-connect-databases/

**Comment by zztkm** [comment]
It seems to be stuck on draft pr. Is there anything I can do to help?

**Comment by syumai** [comment]
@zztkm Thank you for offering your assistance.
I will have time to work on this issue over the weekend, so if I encounter anything difficult, I will let you know.
Please wait for a while 🙏

**Comment by syumai** [comment]
#65 is released as [v0.21.0](https://github.com/syumai/workers/releases/tag/v0.21.0).
