### ISSUE TITLE
fetching a binary file returns a corrupted body

### ISSUE THREAD

**Issue by jagobagascon** [syumai/workers#70]
Hi! I'm using the `fetch.NewRequest` to build a proxy and serve files from a remote server, but non-text files are getting corrupted. The logs show the following warning:

```
Called .text() on an HTTP body which does not appear to be text. The body's Content-Type is "image/png". The result will probably be corrupted. Consider checking the Content-Type header before interpreting entities as text.
```

I was able to make it work by implementing my own `toResponse` function where I read the data from the `blob`.

**Comment by syumai** [comment]
@jagobagascon Thank you for reporting this issue!
This issue is solved in #78 and released as https://github.com/syumai/workers/releases/tag/v0.19.0.
