### ISSUE TITLE
Using "html/template"

### ISSUE THREAD

**Issue by Izdatyi** [syumai/workers#89]
Hi
I try to use templates, but got error
Is this supported ?
Thanks

```go
import (
	...
	"html/template"
)

func main() {
	http.HandleFunc("/test", func(w http.ResponseWriter, r *http.Request) {
		tmpl, _ := template.New("foo").Parse(`<div>{{.CounterValue}}</div>`)

		data := map[string]int{
			"CounterValue": 10,
		}
		_ = tmpl.ExecuteTemplate(w, "foo", data)
	})
	workers.Serve(nil)
}
```

![2024-01-20 122112](https://github.com/syumai/workers/assets/7038127/63f7e703-3a0b-441d-a66c-bca16ea9eb4f)

**Comment by syumai** [comment]
@Izdatyi
According to the error message, it seems to be a problem with TinyGo's reflect package.

```
- Exception Thrown @ 1/20/2024, 9:40:40 PM
  (log) panic: unimplemented: (reflect.Type).NumOut()
```

Same code in Go (not TinyGo) worked.

---

* examples:
  - [tinygo-html-template](https://github.com/syumai/workers-playground/tree/main/tinygo-html-template)
  - [go-html-template](https://github.com/syumai/workers-playground/tree/main/go-html-template)

**Comment by Izdatyi** [comment]
More likely
I'm using an alternative for now https://github.com/valyala/fasttemplate
Works fine
