### ISSUE TITLE
Cache example doesn't cache when deployed to Cloudflare

### ISSUE THREAD

**Issue by TheMightyGit** [syumai/workers#95]
If I repeatedly curl the cache example (`_examples/cache`) I get a different response each time, no caching happens.

This only happens when deployed to cloudflare. When run in wrangler local dev it caches fine.

**Comment by syumai** [comment]
@TheMightyGit 
Are you using the `*.workers.dev` subdomain?
[It is not attached to your domain](https://developers.cloudflare.com/workers/configuration/routing/routes/#routes-with-workersdev) and therefore does not affect the cache.
If you are using your own domain, I would look into this issue further.

**Comment by TheMightyGit** [comment]
> @TheMightyGit Are you using the `*.workers.dev` subdomain? [It is not attached to your domain](https://developers.cloudflare.com/workers/configuration/routing/routes/#routes-with-workersdev) and therefore does not affect the cache. If you are using your own domain, I would look into this issue further.

Ah! Yes, I am using the `*.workers.dev`. Thank you for the answer :)
